# Generated by Django 3.2.13 on 2022-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kill_cnt',
            field=models.BigIntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lose_cnt',
            field=models.BigIntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='win_cnt',
            field=models.BigIntegerField(default=int),
            preserve_default=False,
        ),
    ]
