# Generated by Django 3.2.13 on 2022-10-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221013_1546'),
        ('accounts', '0004_user_followings'),
    ]

    operations = [
    ]
