# Generated by Django 3.2.13 on 2022-11-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='like_or_hate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
