# Generated by Django 3.2.13 on 2022-11-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_survey_like_or_hate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='like_or_hate',
            field=models.IntegerField(choices=[(0, 'like'), (1, 'normal'), (2, 'hate')], default=1),
        ),
    ]
